name: Best Movies Azure Static Web Apps CI/CD Pipeline

env:
  APP_LOCATION: "BestMovies.WebApp" # location of your client code
  API_LOCATION: "BestMovies.Bff"    # location of your api source code - optional
  OUTPUT_LOCATION: "wwwroot"        # location of client code build output
  DOTNET_VERSION: '6.0.x'
  OUTPUT_PATH: './BestMovies.Bff/output'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore './BestMovies.Api/BestMovies.Bff.Test.csproj'

      - name: Build
        run: dotnet publish './BestMovies.Api/BestMovies.Bff.csproj' --configuration Release --output ${{ env.OUTPUT_PATH }}
        
      - name: Test
        run: dotnet test './BestMovies.Api/BestMovies.Bff.Test.csproj' --no-restore --verbosity normal

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.OUTPUT_LOCATION }}