name: Best Movies Azure Static Web Apps CI/CD Pipeline

env:
  APP_LOCATION: "BestMovies.WebApp" # location of your client code
  API_LOCATION: "BestMovies.Bff"    # location of your api source code - optional
  OUTPUT_LOCATION: "wwwroot"        # location of client code build output

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.OUTPUT_LOCATION }}