name: Movies_API_CI/CD
on: 
  push:
      branches:
        - master
  workflow_dispatch:

env:
    LOCATION: westeurope
    DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build './BestMovies.Api/BestMovies.Api.csproj' --configuration Release --output ./BestMovies.Api/output
      
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: './BestMovies.Api/output'
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: './BestMovies.Api/output'


    - name: Deploy Functions App
      uses: Azure/functions-action@v1
      with:
        app-name: 'fn-bestmovies-api-prod'
        package: './BestMovies.Api/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}