name: Best Movies API CI/CD Pipeline
on: 
  push:
      branches:
        - main
      paths:
        - ".github/workflows/**"
        - "BestMovies.Shared/**"
        - "BestMovies.Api/**"
  workflow_dispatch:

env:
    DOTNET_VERSION: '6.0.x'
    OUTPUT_PATH: './BestMovies.Api/output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet publish './BestMovies.Api/BestMovies.Api.csproj' --configuration Release --output ${{ env.OUTPUT_PATH }}
      
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ env.OUTPUT_PATH }}
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ${{ env.OUTPUT_PATH }}


    - name: Deploy Functions App
      uses: Azure/functions-action@v1
      with:
        app-name: 'fn-bestmovies-api-prod'
        package: ${{ env.OUTPUT_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}